server:
  port: 8080

spring:
  cloud:
    gateway:
      routes:
        - id: auth-service
          uri: lb://auth-service
          predicates:
            - Path=/gateway/auth/**
          filters:
            - RewritePath=/gateway/auth/(?<segment>.*), /api/v1/auth/${segment}
        - id: delivery-service
          uri: lb://delivery-service
          predicates:
            - Path=/gateway/deliveries/**
          filters:
            - RewritePath=/gateway/deliveries/(?<segment>.*), /api/v1/deliveries/${segment}
        - id: tracking-service
          uri: lb://tracking-service
          predicates:
            - Path=/gateway/tracking/**
          filters:
            - RewritePath=/gateway/tracking/(?<segment>.*), /api/v1/tracking/${segment}
        - id: admin-service
          uri: lb://admin-service
          predicates:
            - Path=/gateway/admin/**
          filters:
            - RewritePath=/gateway/admin/(?<segment>.*), /api/v1/admin/${segment}
