server:
  port: 8080

spring:
  cloud:
    gateway:
      routes:
        - id: auth-service-docs
          uri: lb://auth-service
          predicates:
            - Path=/v3/api-docs/auth-service
          filters:
            - RewritePath=/v3/api-docs/auth-service, /v3/api-docs
        - id: delivery-service-docs
          uri: lb://delivery-service
          predicates:
            - Path=/v3/api-docs/delivery-service
          filters:
            - RewritePath=/v3/api-docs/delivery-service, /v3/api-docs
        - id: tracking-service-docs
          uri: lb://tracking-service
          predicates:
            - Path=/v3/api-docs/tracking-service
          filters:
            - RewritePath=/v3/api-docs/tracking-service, /v3/api-docs
        - id: admin-service-docs
          uri: lb://admin-service
          predicates:
            - Path=/v3/api-docs/admin-service
          filters:
            - RewritePath=/v3/api-docs/admin-service, /v3/api-docs
        - id: auth-service
          uri: lb://auth-service
          predicates:
            - Path=/gateway/auth/**
          filters:
            - RewritePath=/gateway/auth/(?<segment>.*), /api/v1/auth/${segment}
        - id: auth-service-native
          uri: lb://auth-service
          predicates:
            - Path=/api/v1/auth/**
        - id: delivery-service
          uri: lb://delivery-service
          predicates:
            - Path=/gateway/deliveries/**
          filters:
            - RewritePath=/gateway/deliveries/(?<segment>.*), /api/v1/deliveries/${segment}
        - id: delivery-service-native
          uri: lb://delivery-service
          predicates:
            - Path=/api/v1/deliveries/**
        - id: tracking-service
          uri: lb://tracking-service
          predicates:
            - Path=/gateway/tracking/**
          filters:
            - RewritePath=/gateway/tracking/(?<segment>.*), /api/v1/tracking/${segment}
        - id: tracking-service-native
          uri: lb://tracking-service
          predicates:
            - Path=/api/v1/tracking/**
        - id: admin-service
          uri: lb://admin-service
          predicates:
            - Path=/gateway/admin/**
          filters:
            - RewritePath=/gateway/admin/(?<segment>.*), /api/v1/admin/${segment}
        - id: admin-service-native
          uri: lb://admin-service
          predicates:
            - Path=/api/v1/admin/**

springdoc:
  swagger-ui:
    disable-swagger-default-url: true
    urls:
      - name: gateway
        url: /v3/api-docs
      - name: auth-service
        url: /v3/api-docs/auth-service
      - name: delivery-service
        url: /v3/api-docs/delivery-service
      - name: tracking-service
        url: /v3/api-docs/tracking-service
      - name: admin-service
        url: /v3/api-docs/admin-service
