security:
  jwt:
    secret: ${JWT_SECRET:ZHVtbXktc21hcnRjb3VyaWVyLXNlY3JldC1rZXktZm9yLWp3dC1zaWduaW5nLTEyMzQ1Njc4OTA=}

springdoc:
  swagger-ui:
    path: /swagger-ui.html

management:
  endpoints:
    web:
      exposure:
        include: health,info

