sonar.projectKey=smartcourier-delivery-management
sonar.projectName=SmartCourier Delivery Management System
sonar.sources=auth-service/src/main,delivery-service/src/main,tracking-service/src/main,admin-service/src/main,api-gateway/src/main,config-server/src/main
sonar.tests=auth-service/src/test,delivery-service/src/test,tracking-service/src/test,admin-service/src/test
sonar.java.binaries=auth-service/target/classes,delivery-service/target/classes,tracking-service/target/classes,admin-service/target/classes,api-gateway/target/classes,config-server/target/classes
sonar.coverage.jacoco.xmlReportPaths=target/site/jacoco-aggregate/jacoco.xml

