server:
  port: 8083

spring:
  application:
    name: tracking-service
  config:
    import: optional:configserver:${CONFIG_SERVER_URL:http://localhost:8888}
  rabbitmq:
    host: ${RABBITMQ_HOST:localhost}
    port: ${RABBITMQ_PORT:5672}
    username: ${RABBITMQ_USERNAME:guest}
    password: ${RABBITMQ_PASSWORD:guest}
  datasource:
    url: jdbc:mysql://${TRACKING_DB_HOST:localhost}:${TRACKING_DB_PORT:3306}/${TRACKING_DB_NAME:smartcourier_tracking}?createDatabaseIfNotExist=true&useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
    username: ${TRACKING_DB_USERNAME:root}
    password: ${TRACKING_DB_PASSWORD:root}
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true

app:
  storage:
    upload-dir: uploads/tracking

security:
  jwt:
    secret: ZHVtbXktc21hcnRjb3VyaWVyLXNlY3JldC1rZXktZm9yLWp3dC1zaWduaW5nLTEyMzQ1Njc4OTA=

eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_SERVER_URL:http://localhost:8761/eureka}
  instance:
    prefer-ip-address: true

management:
  endpoints:
    web:
      exposure:
        include: health,info

springdoc:
  swagger-ui:
    path: /swagger-ui.html
